Feature/boilers types
SantiagoGigli/RR-CaldAR-T3 pull request #1
Opened 2020-11-23 15:08 UTC by emilianobarro8

Boilers Types DATA and CONTROLLERS creation.

2020-11-24 20:51 UTC, davidcurras requested changes
Te hice varias correcciones que se repiten en mas lugares que los que te comente. Por favor cambia todo y marcalo como corregido cuando termines.

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +const dir_json='../data/boilers-types.json';
Esta variable deberia seguir el formato de variables definido. dirJson o dataDir

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +const fs= require('fs');
No hay espacio antes del = mientras que en los demas si lo hay

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +const router=express.Router();
No hay espacio antes y despues del igual, mientras que en los demas si los hay

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +  console.log('getBoilersTypesByType:'+type);
Deberiamos limpiar los console.log al momento de hacer push.

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +  const found=boilers_types.some(boiler_type=>boiler_type.description.substring(5,6)==type);
Deberiamos siempre usar comparaciones con triple igual ===
Ademas faltan espacios antes y despues de la asignacion = y de la arrow funcion =>

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +    res.status(400).json({msg: 'Boiler type with type '+ type + ' not found.' });
O sobra un espacio antes de cerrar la llave } o falta un espacio al abrirla {

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +  console.log('getAllBoilersTypes');
Sacar este console.log

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +
Este espacio en blanco esta de mas. Dejamos un espacio entre ruta y ruta

2020-11-24 20:51 UTC, davidcurras commented on controllers/boilers-types.js
> +module.exports=router;
Hay mas errores del mismo estilo que te marque antes, corregi todo 🙏 
Ademas deberiamos siempre dejar un renglon en blanco al final de cada archivo.

2020-11-24 20:51 UTC, davidcurras commented on index.js
> +app.use('/boilers-types', require('./controllers/boilers-types'));
Este require deberia ir al principio, en la linea 2, guardarlo en una variable y despues usarlo aca.

2020-11-25 03:25 UTC, davidcurras approved these changes

2020-11-26 00:14 UTC, ignacioaristo approved these changes

2020-11-26 00:29 UTC, merged