Feature/boilers mongo
SantiagoGigli/RR-CaldAR-T3 pull request #16
Opened 2020-11-30 02:01 UTC by arltaugusto

2020-12-02 03:09 UTC, davidcurras requested changes
Dado que en este caso usar Async y Await te obliga a hacer un try y catch y que los demás integrantes del equipo eligieron promesas, deberías pasar todo a promesas en lugar de Async Await

2020-12-03 14:08 UTC, ignacioaristo approved these changes

2020-12-03 14:09 UTC, ignacioaristo approved these changes

2020-12-04 11:15 UTC, ignacioaristo approved these changes

2020-12-05 02:28 UTC, davidcurras approved these changes

2020-12-05 02:28 UTC, merged