Feature/costumers
SantiagoGigli/RR-CaldAR-T3 pull request #25
Opened 2020-12-10 03:19 UTC by MarianaBS

2020-12-10 20:49 UTC, davidcurras requested changes
Hay 3 detalles, pero lo mas grave es el archivo env.
Corre el comando `git remove ./env` para borrar el archivo antes de hacer commit y corregir los cambios.

2020-12-10 20:49 UTC, davidcurras commented on controllers/customers.js
> +// eslint-disable-next-line prefer-destructuring
No deberiamos deshabilitar eslint en una linea.
Si hay alguna regla que queremos cambiar la charlamos con el equipo y si todos estan de acuerdo hacemos el refactor para cambiar todos los archivos.

2020-12-10 20:49 UTC, davidcurras commented on controllers/customers.js
> +          message: `Cannot update Customer with id = ${ObjectID(req.params.id)}. Maybe Customer was not found`,
Simplifiquemos el mensaje. Algo asi mejor:
`User ${req.params.id} not found`

2020-12-10 20:49 UTC, davidcurras commented on env
> +mongoURL = mongodb+srv://IgnacioAristo:radium1234@caldar.ejvrp.mongodb.net/caldar?retryWrites=true&w=majority
Este archivo deberia tener un . al principio .env
Y no debe hacerse commit NUNCA de nombres de usuario y claves, menos en repositorios publicos.

2020-12-10 23:42 UTC, MarianaBS commented on env
> +mongoURL = mongodb+srv://IgnacioAristo:radium1234@caldar.ejvrp.mongodb.net/caldar?retryWrites=true&w=majority
Lo sabía, no me di cuenta!

2020-12-11 03:07 UTC, davidcurras approved these changes

2020-12-11 11:40 UTC, ignacioaristo approved these changes

2020-12-11 11:41 UTC, merged