Feature/appointments
SantiagoGigli/RR-CaldAR-T3 pull request #6
Opened 2020-11-24 01:23 UTC by arltaugusto

2020-11-24 21:12 UTC, davidcurras requested changes

2020-11-24 21:12 UTC, davidcurras commented on utils/ABMUtils.js
> +}
Entiendo que decidiste abstraer la funcionalidad en un archivo separado para reutilzar codigo. Hay un punto donde la abstraccion tambien es un problema. El codigo que crece verticalmente se abstrae para reutilizarlo y empieza a crecer horizontalmente. Pero mucha abstraccion genera confusion, es dificil de mantener y en muchos casos innecesario. Consume mas tiempo pensar en como reutilizar la funcion que en duplicar un par de lineas.
En cualquiera de los casos, deberias escribir las funciones getById, getByAttribute, etc como funciones en la linea 2, y dentro del module.exports hacer refecencia a los nombres de funciones y constantes a exportar.

2020-11-25 01:39 UTC, emilianobarro8 commented on controllers/appointments.js
> +    const areArraysEqual = entityAttrs.every((val, index) => val == queryAttr[index])
Falta ; linea 27

2020-11-25 01:59 UTC, emilianobarro8 approved these changes

2020-11-25 03:37 UTC, davidcurras approved these changes

2020-11-25 22:46 UTC, merged