Feature/technicians
SantiagoGigli/RR-CaldAR-T3 pull request #8
Opened 2020-11-24 21:06 UTC by ignacioaristo

First PR!

2020-11-24 21:22 UTC, davidcurras requested changes

2020-11-24 21:22 UTC, davidcurras commented on controllers/technicians.js
> +
Este espacio en blanco, y los demas (linea 13, linea 19, etc) no deberian estar

2020-11-24 21:22 UTC, davidcurras commented on controllers/technicians.js
> +  res.json(technicians.filter(tech => tech.id === parseInt(req.query.id)));
Deberiamos hacer una validacion luego de filtrar. Si no encuentra el objeto devuelvo codigo 404.

2020-11-24 21:22 UTC, davidcurras commented on controllers/technicians.js
> +      }
Esta linea esta mal indentada

2020-11-24 21:22 UTC, davidcurras commented on controllers/technicians.js
> +        res.json({msg: `Technician ${req.params.id} deleted`, Technicians: techniciansLeft });
Techinitians: deberia ir con minuscula

2020-11-24 21:22 UTC, davidcurras commented on controllers/technicians.js
> +    }	else{
Deberiamos dejar espacio antes del else

2020-11-24 21:22 UTC, davidcurras commented on controllers/technicians.js
> +  const techniciansLeft = technicians.filter(tech => tech.id !== parseInt(req.query.id));
Antes de esta linea deberiamos revisar si hay algun Technitian con ese id, usando Find y en caso que no haya devolver 404.

2020-11-24 21:22 UTC, davidcurras commented on index.js
> +app.use('/', require('./controllers/technicians'));
Este require deberia ser una constante en la linea 2 y usarla aca

2020-11-24 23:53 UTC, emilianobarro8 approved these changes

2020-11-25 03:30 UTC, davidcurras approved these changes

2020-11-25 04:06 UTC, merged